### ISSUE TITLE
v1.1.0 CS0246 'ONSPAudioSource' could not be found missing a using directive or an assembly reference error

### ISSUE THREAD

**Issue by junebug12851** [vrchat-community/ClientSim#6]
I imported this url into package manager which imports version `1.1.0` specifically. 
`https://github.com/vrchat-community/ClientSim.git#1.1.0`

and I get 2 issues as soon as I import it

```
Library\PackageCache\com.vrchat.clientsim@7b3a59c809\Runtime\Helpers\ClientSimSpatialAudioHelper.cs(8,48): error CS0246: The type or namespace name 'ONSPAudioSource' could not be found (are you missing a using directive or an assembly reference?)
```

```
Library\PackageCache\com.vrchat.clientsim@7b3a59c809\Runtime\Helpers\ClientSimSpatialAudioHelper.cs(15,17): error CS0246: The type or namespace name 'ONSPAudioSource' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by NarryG** [comment]
You'll need to import the updated package-manager based SDK and not the old UnityPackage SDK due to how Unity handles dependencies with packages, or else certain imports won't work as expected.

**Comment by junebug12851** [comment]
What's the `updated package-manager based SDK`

**Comment by zhdlxh48** [comment]
I have also same problem... what is 

> updated package-manager based SDK

Please help this problem... @NarryG

**Comment by CyanLaser** [comment]
@junebug12851 @zhdlxh48 The package-manager based SDK is the sdk uploaded to github at vrchat/packages. ClientSim also lists its dependencies in the package.json. Just as you used the git link to install ClientSim in unity, use these two links to import the package version of the sdk:
https://github.com/vrchat-community/ClientSim/blob/7b3a59c809730f8d47da31f3aeaa93e42e88786f/package.json#L12-L13

**Comment by momo-the-monster** [comment]
@oivio:

1. Open the Unity Package Manager, click the + button and choose 'Add package from git URL...'
2. Enter this url: `https://github.com/vrchat/packages.git?path=/packages/com.vrchat.base#3.0.1`. Wait until the package finishes importing (you may need to press CTRL+R to jumpstart the process if you have Auto-Refresh turned off in the Unity Editor)
3. Once complete, choose 'Add package from git URL...' again and enter: `https://github.com/vrchat/packages.git?path=/packages/com.vrchat.worlds#3.0.1`
4. If you haven't already done so, add the ClientSim package: `https://github.com/vrchat-community/ClientSim.git#1.1.0`

Wait for everything to complete. You may need to select VRChat SDK > Reload Plugins from the top menu to finalize the plugin loading, then you should be ready to use everything together. Note that this approach is meant for experienced Unity users, the upcoming VRChat Creator Companion will handle most of this for you.

@junebug12851 - are you still having an issue with ONSPAudioSource?

**Comment by Adam-Kay** [comment]
@momo-the-monster Does the ordinary SDK have to be completely removed before attempting to install this package version?

**Comment by pavlov3-progress** [comment]
I have the same problem.
Your opinion will be helpful.
Thank you very much.
( I use the Google translation app for help )

@Adam-Kay 
The screen display of this screenshot is displayed.
Let me show you how.
![image](https://user-images.githubusercontent.com/51938268/161587050-da07e818-e984-42ca-9319-a8ae8732bcd7.png)
1. Make Project
2. Open the Unity Package Manager, click the + button and choose 'Add package from git URL...' 
Enter url :
```https://github.com/vrchat/packages.git?path=/packages/com.vrchat.base#3.0.1```
done. Enter next url : 
```https://github.com/vrchat/packages.git?path=/packages/com.vrchat.worlds#3.0.1```
done. Enter next url : 
```https://github.com/vrchat-community/ClientSim.git#1.1.0```
4. Assets -> Import Package -> Custom Package
import ```VRCSDK3-WORLD unitypackage``` 
5. Press ```Yes``` ( editer will be rebooted )
![import_CSim_Warning](https://user-images.githubusercontent.com/51938268/161592649-73796981-ed0b-4352-82d9-343b3d3e6139.png)

5. Press the play button

**Comment by Adam-Kay** [comment]
Unfortunately, this process didn't work for me, I am not able to access the VRCSDK control panel after following your steps, the option isn't available in Unity:
![image](https://user-images.githubusercontent.com/10010491/162215266-82b9a38f-adec-44d2-942a-8e5b1a3d48ef.png)

I have tried every way I can think of to install this into my existing project: Following @pavlov3-progress's instructions, removing the original SDK3 first, trying to install it after the 3 packages, trying without, deleting the Library folder and letting Unity rebuild it etc. Usually I either can't access the VRCSDK panel, I get 999+ errors, or pressing Play doesn't do anything different than it did before.

I'm not sure if I'm doing it wrong, but I may leave it for now until the VRChat Creator Companion eventually releases to help with this

**Comment by abcaad** [comment]
1. Remove old sdk and udonsharp
2. Package Manager > Add package from git URL...
`https://github.com/vrchat/packages.git?path=/packages/com.vrchat.base#3.0.1`
`https://github.com/vrchat/packages.git?path=/packages/com.vrchat.worlds#3.0.1`
`https://github.com/vrchat-community/ClientSim.git#1.1.0`
VRChat SDK - Worlds > samples > import into Project
3. Assets -> Import Package -> Custom Package
  import UdonSharp.unitypackage
4. Close Project  
    Delete `projectfolder/*.csproj`    `projectfolder/*.sln`
5. Open Project 
    Assets > Reimport All

**Comment by Conmiro** [comment]
> 1. Remove old sdk and udonsharp
> 2. Package Manager > Add package from git URL...
>    `https://github.com/vrchat/packages.git?path=/packages/com.vrchat.base#3.0.1`
>    `https://github.com/vrchat/packages.git?path=/packages/com.vrchat.worlds#3.0.1`
>    `https://github.com/vrchat-community/ClientSim.git#1.1.0`
>    VRChat SDK - Worlds > samples > import into Project
> 3. Assets -> Import Package -> Custom Package
>    import UdonSharp.unitypackage
> 4. Close Project
>    Delete `projectfolder/*.csproj`    `projectfolder/*.sln`
> 5. Open Project
>    Assets > Reimport All
> 
> I don't know which operations are redundant.

Followed these steps exactly, and did not work. Get three variations of the below message:

`Assembly 'Assets/VRCSDK/Dependencies/Managed/Microsoft.CodeAnalysis.CSharp.dll' will not be loaded due to errors:
Microsoft.CodeAnalysis.CSharp references strong named System.Collections.Immutable Assembly references: 1.2.1.0 Found in project: 5.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
`
This error is thrown for the 3 dll's that UdonSharp brought into Assets/VRCSDK/Dependencies/Managed. I'm not sure why UdonSharp is bringing in items under a folder for VRCSDK assets, but that seems to be the cause of the error.

These errors are not there when you bring in the VRChat SDK via Assets -> Import Package -> Custom Package, but then there are the errors that OP mentioned.

**Comment by momo-the-monster** [comment]
@Conmiro @junebug12851 - are these issues still present for you when using ClientSim 1.2.2 via [the Creator Companion](https://vcc.docs.vrchat.com)?

**Comment by cubedparadox** [comment]
I'm going to close this issue out due to inactivity + out of date packages.
If you encounter similar issues using the latest version of ClientSim via the Creator Companion, feel free to open a new issue!
